server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: microservice
          uri: http://localhost:8081
          predicates:
            - Path=/microservice/**
        - id: SpringBoot
          uri: http://localhost:8080
          predicates:
            - Path=/SpringBoot/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
