spring:
  application:
    name: SpringBoot
  datasource:
    url: jdbc:postgresql://localhost:5432/learning
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  zipkin:
    baseUrl: http://localhost:9411
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  cloud:
    loadbalancer:
      retry:
        enabled: true
  bus:
    enabled: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
management:
  metrics:
    export:
      zipkin:
        enabled: true
        base-url: http://localhost:9411
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
application:
  version: springboot-v5
  
